package com.sickworm.intellij.jugg

import com.intellij.openapi.diagnostic.Logger
import com.sickworm.intellij.jugg.apk.ApkFileUnit
import com.sickworm.intellij.jugg.apk.ApkInfo
import com.sickworm.intellij.jugg.compiler.manifest.XmlParser
import com.sickworm.intellij.jugg.compiler.manifest.get
import com.sickworm.intellij.jugg.logger.TimeLogger
import com.sickworm.intellij.jugg.project.data.ModuleInfo

/**
 * ModuleApkBelongsUtils resolves module-to-APK ownership across base and dynamic-feature APK artifacts.
 * Collaboration: Reads split metadata from merged manifests via [XmlParser.parse], enriches per-apk state in [ApkModuleBelongsData], and returns mapping consumed by compile/deploy flows.
 * Data Contract: [tempModule] always maps to the base APK (or first APK fallback when base is missing), and unresolved modules fall back to base APK for robustness.
 */
object ModuleApkBelongsUtils {


    fun getModuleApkBelongs(
        applicationModule: ModuleInfo?,
        apkInfo: List<ApkInfo>,
        modules: Map<String, ModuleInfo>,
        tempModule: ModuleInfo,
        logger: Logger,
    ): ModuleApkBelongs {
        val apkFiles = apkInfo.flatMap { it.files }
        if (apkFiles.isEmpty()) {
            return ModuleApkBelongs(emptyMap(), emptyMap())
        }
        if (apkFiles.size == 1) {
            val singleMap = (modules.values + tempModule).associateWith { apkFiles.first() }
            return ModuleApkBelongs(singleMap, singleMap.mapValues { listOf(it.value) })
        }

        TimeLogger.start("getModuleApkBelongs")

        // 1. group the module type.
        // It will be used to determine the apk belongs to which module with priority
        // if not found, otherModules will be used
        val applicationModules = if (applicationModule != null) {
            setOf(applicationModule)
        } else {
            modules.values.filter { it.moduleType == ModuleInfo.Type.Application }.toMutableSet()
        }
        val dynamicFeatureModules = modules.values.filter { it.moduleType == ModuleInfo.Type.DynamicFeature }.toSet()
        val otherModules = modules.values - applicationModules - dynamicFeatureModules
        logger.debug("getModuleApkBelongs: applicationModule: ${applicationModules.map { it.name }}, " +
                "dynamicFeatureModule: ${dynamicFeatureModules.map { it.name }}, " +
                "otherModules: ${otherModules.map { it.name }}")

        // 2. bind the apks with the modules by featureSplit in AndroidManifest.xml
        val apkModuleBelongsData = apkFiles.map {
            ApkModuleBelongsData(it)
        }
        // priority find it in dynamicFeatureModules
        val dynamicModuleToFeatures = modules.values.associateBy { it.getSplitFeature() }
        apkModuleBelongsData.forEach {
            val featureModule = dynamicModuleToFeatures[it.moduleName]
            if (featureModule != null) {
                it.featureGeneratedModule = featureModule
            }
        }
        logger.debug("match apk to module: ${apkModuleBelongsData.joinToString { "${it.fileName} -> ${it.featureGeneratedModule?.name}" }}")
        val remainApkModuleBelongsData = apkModuleBelongsData.filter { it.isFeatureApk && it.featureGeneratedModule == null }
        logger.debug("remain apk: ${remainApkModuleBelongsData.joinToString { "${it.fileName} -> ${it.moduleName}" }}")
        if (remainApkModuleBelongsData.isNotEmpty()) {
            // find it in other modules in case ModuleInfo.moduleType it's not working
            val otherModuleToApk = (applicationModules + otherModules).associateBy { it.getSplitFeature() }
            remainApkModuleBelongsData.forEach {
                val featureModule = otherModuleToApk[it.moduleName]
                if (featureModule != null) {
                    it.featureGeneratedModule = featureModule
                }
            }
            logger.debug("remain apk after search other modules: ${remainApkModuleBelongsData.joinToString { "${it.fileName} -> ${it.moduleName}" }}")
            // if there is still remain apk, it means the apk is not generated by any module, ignore it for robustness
        }

        // 3. find out the module belongs to which apk.
        // If module is dependent on application module, then it's belong to base apk
        val moduleApkBelongs = mutableMapOf<ModuleInfo, ApkFileUnit>()
        val allModuleApkBelongs = mutableMapOf<ModuleInfo, MutableList<ApkFileUnit>>()
        var baseApk = apkModuleBelongsData.find { it.isBaseApk }?.apkFileUnit
        if (baseApk == null) {
            // it should not happen, but it's better to ignore it and see what will happen in the future
            logger.debug("getModuleApkBelongs: base apk not found, apkFiles: ${apkFiles.joinToString { it.apkFile.name }}")
            baseApk = apkModuleBelongsData.first().apkFileUnit
            logger.debug("getModuleApkBelongs: base apk not found, use the first apk: $baseApk")
        } else {
            logger.debug("getModuleApkBelongs: base apk: $baseApk")
        }
        // Step 0: androidTest modules map directly to the matching test ApkFileUnit.
        // This must run before all other routing so test modules are never
        // accidentally routed to the base or dynamic-feature APK.
        val testApkByTargetPkg: Map<String, ApkFileUnit> = apkInfo
            .filter { it.isTestApk }
            .mapNotNull { info ->
                val unit = info.files.firstOrNull() ?: return@mapNotNull null
                val pkg = info.instrumentationTargetPackage ?: return@mapNotNull null
                pkg to unit
            }
            .toMap()

        modules.values
            .filter { it.isAndroidTestModule }
            .forEach { testModule ->
                val unit = testApkByTargetPkg[testModule.instrumentationTargetPackage]
                if (unit != null) {
                    moduleApkBelongs[testModule] = unit
                    allModuleApkBelongs.getOrPut(testModule) { mutableListOf() }.add(unit)
                }
                // if no test apk found, fall through to normal routing below (will land on base apk)
            }

        moduleApkBelongs[tempModule] = baseApk
        val tempBelongs = allModuleApkBelongs.getOrPut(tempModule) { mutableListOf() }
        tempBelongs.add(baseApk)
        testApkByTargetPkg.values.forEach { unit ->
            if (unit !in tempBelongs) {
                tempBelongs.add(unit)
            }
        }
        val modulesInBaseApk = findAllDependModules(applicationModules, modules)
        apkModuleBelongsData.forEach {
            if (it.isFeatureApk && it.featureGeneratedModule != null) {
                it.subModules = findAllDependModules(setOf(it.featureGeneratedModule!!), modules)
            }
        }
        modules.values.forEach { moduleInfo ->
            // skip modules already routed (e.g. androidTest modules resolved in Step 0)
            if (moduleInfo in moduleApkBelongs) {
                return@forEach
            }
            // if module is dependent on application module, then it's belong to base apk
            if (moduleInfo in modulesInBaseApk) {
                moduleApkBelongs[moduleInfo] = baseApk
                allModuleApkBelongs.getOrPut(moduleInfo) { mutableListOf() }.add(baseApk)
                return@forEach
            }
            // if module is dependent on dynamic feature module, then it's belong to dynamic feature apk
            apkModuleBelongsData.forEach inner@{
                if (it.featureGeneratedModule != null && (moduleInfo in it.subModules)) {
                    moduleApkBelongs[moduleInfo] = it.apkFileUnit
                    allModuleApkBelongs.getOrPut(moduleInfo) { mutableListOf() }.add(it.apkFileUnit)
                    return@forEach
                }
            }
            // if module is not dependent on any module, then it's belong to base apk for fallback
            moduleApkBelongs[moduleInfo] = baseApk
            allModuleApkBelongs.getOrPut(moduleInfo) { mutableListOf() }.add(baseApk)
        }

        @Suppress("NestedLambdaShadowedImplicitParameter")
        val resultLogString = moduleApkBelongs.entries
            .groupBy { it.value.apkFile.name }
            .entries.joinToString { "${it.key} -> [${it.value.joinToString { it.key.name } }]" }
        logger.debug("moduleApkBelongs result: $resultLogString")
        TimeLogger.end("getModuleApkBelongs", logger)
        return ModuleApkBelongs(
            moduleApkBelongs,
            allModuleApkBelongs.mapValues { it.value.distinct() },
        )
    }

    private fun ModuleInfo.getSplitFeature(): String? {
        val mergedManifest = this.buildPathInfo.mergedManifest
        if (!mergedManifest.exists()) {
            return null
        }
        return XmlParser().parse(mergedManifest).node["featureSplit"]
    }

    private fun findAllDependModules(topModules: Collection<ModuleInfo>, allModules: Map<String, ModuleInfo>): List<ModuleInfo> {
        val result = topModules.toMutableSet()
        var findingModules = topModules.toMutableSet()
        while (findingModules.isNotEmpty()) {
            val nextFindingModules = mutableSetOf<ModuleInfo>()
            findingModules.forEach { module ->
                val modules = module.moduleDependencies.mapNotNull { allModules[it.moduleName] }
                modules.forEach { subModule ->
                    if (subModule !in result) {
                        result.add(subModule)
                        nextFindingModules.add(subModule)
                    }
                }
            }
            findingModules = nextFindingModules
        }
        return result.toList()
    }

    /**
     * ApkModuleBelongsData working item for one APK while resolving module-to-APK ownership in [ModuleApkBelongsUtils.getModuleApkBelongs].
     */
    private class ApkModuleBelongsData(
        var apkFileUnit: ApkFileUnit,
        var featureGeneratedModule: ModuleInfo? = null,
        var subModules: List<ModuleInfo> = emptyList(),
    ) {
        val isBaseApk: Boolean get() = apkFileUnit.isBaseApk
        val isFeatureApk: Boolean get() = apkFileUnit.isFeatureApk
        val moduleName: String get() = apkFileUnit.moduleName
        val fileName: String get() = apkFileUnit.apkFile.name
    }
}
