package com.sickworm.intellij.jugg

import com.intellij.openapi.diagnostic.Logger
import com.sickworm.intellij.jugg.compiler.manifest.XmlParser
import com.sickworm.intellij.jugg.compiler.manifest.get
import com.sickworm.intellij.jugg.logger.TimeLogger
import com.sickworm.intellij.jugg.platform.PlatformApi
import com.sickworm.intellij.jugg.project.data.ModuleInfo
import java.io.File

/**
 * Find out which apk a module belongs to.
 */
object ModuleApkBelongsUtils {


    fun getModuleApkBelongs(
        applicationModule: ModuleInfo?,
        apkFiles: List<File>,
        modules: Map<String, ModuleInfo>,
        tempModule: ModuleInfo,
        logger: Logger,
    ): Map<ModuleInfo, File> {
        if (apkFiles.isEmpty()) {
            return emptyMap()
        }
        if (apkFiles.size == 1) {
            return (modules.values + tempModule).associateWith { apkFiles.first() }
        }

        TimeLogger.start("getModuleApkBelongs")

        // 1. group the module type.
        // It will be used to determine the apk belongs to which module with priority
        // if not found, otherModules will be used
        val applicationModules = if (applicationModule != null) {
            setOf(applicationModule)
        } else {
            modules.values.filter { it.moduleType == ModuleInfo.Type.Application }.toMutableSet()
        }
        val dynamicFeatureModules = modules.values.filter { it.moduleType == ModuleInfo.Type.DynamicFeature }.toSet()
        val otherModules = modules.values - applicationModules - dynamicFeatureModules
        logger.debug("getModuleApkBelongs: applicationModule: ${applicationModules.map { it.name }}, " +
                "dynamicFeatureModule: ${dynamicFeatureModules.map { it.name }}, " +
                "otherModules: ${otherModules.map { it.name }}")

        // 2. bind the apks with the modules by featureSplit in AndroidManifest.xml
        val apkModuleBelongsData = apkFiles.map {
            val manifestInfo = PlatformApi.impl.readApkManifest(it, logger)
            ApkModuleBelongsData(
                apkFile = it,
                featureSplit = manifestInfo.featureSplit(),
            )
        }
        // priority find it in dynamicFeatureModules
        val dynamicModuleToFeatures = modules.values.associateBy { it.getSplitFeature() }
        apkModuleBelongsData.forEach {
            val featureModule = dynamicModuleToFeatures[it.featureSplit]
            if (featureModule != null) {
                it.featureGeneratedModule = featureModule
            }
        }
        logger.debug("match apk to module: ${apkModuleBelongsData.joinToString { "${it.apkFile.name} -> ${it.featureGeneratedModule?.name}" }}")
        val remainApkModuleBelongsData = apkModuleBelongsData.filter { it.featureSplit != null && it.featureGeneratedModule == null }
        logger.debug("remain apk: ${remainApkModuleBelongsData.joinToString { "${it.apkFile.name} -> ${it.featureSplit}" }}")
        if (remainApkModuleBelongsData.isNotEmpty()) {
            // find it in other modules in case ModuleInfo.moduleType it's not working
            val otherModuleToApk = (applicationModules + otherModules).associateBy { it.getSplitFeature() }
            remainApkModuleBelongsData.forEach {
                val featureModule = otherModuleToApk[it.featureSplit]
                if (featureModule != null) {
                    it.featureGeneratedModule = featureModule
                }
            }
            logger.debug("remain apk after search other modules: ${remainApkModuleBelongsData.joinToString { "${it.apkFile.name} -> ${it.featureSplit}" }}")
            // if there is still remain apk, it means the apk is not generated by any module, ignore it for robustness
        }

        // 3. find out the module belongs to which apk.
        // If module is dependent on application module, then it's belong to base apk
        val moduleApkBelongs = mutableMapOf<ModuleInfo, File>()
        var baseApk = apkModuleBelongsData.find { it.featureSplit == null }?.apkFile
        if (baseApk == null) {
            // it should not happen, but it's better to ignore it and see what will happen in the future
            logger.debug("getModuleApkBelongs: base apk not found, apkFiles: ${apkFiles.joinToString { it.name }}")
            baseApk = apkModuleBelongsData.first().apkFile
            logger.debug("getModuleApkBelongs: base apk not found, use the first apk: $baseApk")
        } else {
            logger.debug("getModuleApkBelongs: base apk: $baseApk")
        }
        moduleApkBelongs[tempModule] = baseApk
        val modulesInBaseApk = findAllDependModules(applicationModules, modules)
        apkModuleBelongsData.forEach {
            if (it.featureSplit != null && it.featureGeneratedModule != null) {
                it.subModules = findAllDependModules(setOf(it.featureGeneratedModule!!), modules)
            }
        }
        modules.values.forEach { moduleInfo ->
            // if module is dependent on application module, then it's belong to base apk
            if (moduleInfo in modulesInBaseApk) {
                moduleApkBelongs[moduleInfo] = baseApk
                return@forEach
            }
            // if module is dependent on dynamic feature module, then it's belong to dynamic feature apk
            apkModuleBelongsData.forEach inner@{
                if (it.featureGeneratedModule != null && (moduleInfo in it.subModules)) {
                    moduleApkBelongs[moduleInfo] = it.apkFile
                    return@forEach
                }
            }
            // if module is not dependent on any module, then it's belong to base apk for fallback
            moduleApkBelongs[moduleInfo] = baseApk
        }

        @Suppress("NestedLambdaShadowedImplicitParameter")
        val resultLogString = moduleApkBelongs.entries
            .groupBy { it.value.name }
            .entries.joinToString { "${it.key} -> [${it.value.joinToString { it.key.name } }]" }
        logger.debug("moduleApkBelongs result: $resultLogString")
        TimeLogger.end("getModuleApkBelongs", logger)
        return moduleApkBelongs
    }

    private fun ModuleInfo.getSplitFeature(): String? {
        val mergedManifest = this.buildPathInfo.mergedManifest
        if (!mergedManifest.exists()) {
            return null
        }
        return XmlParser().parse(mergedManifest).node["featureSplit"]
    }

    private fun findAllDependModules(topModules: Collection<ModuleInfo>, allModules: Map<String, ModuleInfo>): List<ModuleInfo> {
        val result = topModules.toMutableSet()
        var findingModules = topModules.toMutableSet()
        while (findingModules.isNotEmpty()) {
            val nextFindingModules = mutableSetOf<ModuleInfo>()
            findingModules.forEach { module ->
                val modules = module.moduleDependencies.mapNotNull { allModules[it.moduleName] }
                modules.forEach { subModule ->
                    if (subModule !in result) {
                        result.add(subModule)
                        nextFindingModules.add(subModule)
                    }
                }
            }
            findingModules = nextFindingModules
        }
        return result.toList()
    }

    private class ApkModuleBelongsData(
        var apkFile: File,
        var featureSplit: String?,
        var featureGeneratedModule: ModuleInfo? = null,
        var subModules: List<ModuleInfo> = emptyList(),
    )
}