import org.gradle.internal.jvm.Jvm

plugins {
    id 'org.jetbrains.intellij' version '1.10.1' apply false
    id 'org.jetbrains.kotlin.jvm' version '1.9.23' apply false
//    id 'org.jetbrains.kotlin.jvm' version '2.1.21' apply false
}

def versionName = '3.0.23'
def gitBranch = 'git rev-parse --abbrev-ref HEAD'.execute().text.trim().replace('/', '_')
def gitBranchPrefix = gitBranch == 'main' ? 'release' : (gitBranch == 'develop' ? 'SNAPSHOT' : gitBranch + '-SNAPSHOT')
def pluginVersionArg = "${versionName}-${gitBranchPrefix}"
println("Plugin Version: $pluginVersionArg")

ext {
    // see: https://plugins.jetbrains.com/docs/intellij/android-studio.html#android-studio-releases-listing
    // download Android Studio: https://developer.android.com/studio/archive
//    ide_version = '211.7628.21' // Android Studio Bumblebee
//    ide_version = '212.5712.43' // Android Studio Chipmunk, deployer version 27.2.0.0, don't have GradleSyncListenerWithRoot, while GradleSyncListener won't call back after Giraffe
    ide_version = '223.7571.182' // Android Studio Giraffe
//    ide_version = '231.9225.16' // Android Studio Hedgehog, needs Kotlin 1.9.0 and remove Kotlin Android extension plugin

    agentVersion = "1.0.37"
    agentBundleDir = new File(project.projectDir, "jvmti_agent/build/outputs/bundle/")
    agentGeneratedSourceDir = new File(project.projectDir, "jvmti_agent/build/generated/source/buildConfig/release")

    pluginVersion = pluginVersionArg

    getDirCommitId = { path ->
        def command = "git -C $rootDir log -n 1 --format=%h -- $path"
        def commitHash = command.execute().text.trim()
        println "$path commit hash is: ${commitHash}"
        return commitHash
    }
}

// Fix:
// Entry META-INF/interface.kotlin_module is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.3.3/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
afterEvaluate {
    subprojects {
        it.tasks.withType(Jar).all {
            duplicatesStrategy 'exclude'
        }
    }
}

def currentJvm = Jvm.current()
println("JVM: $currentJvm")
