rootProject.name = 'jugg'

include ':main'
include ':idea'
include ':cmd_line'
include ':cmd_line:standalone_bootstrap'
include ':jvmti_agent'
include ':aapt2-inclink'
include ':custom_compilers'
include ':tools:stub_api_generator'

include ':deploy_compat:interface'
include ':deploy_compat:standalone_deployer'
include ':deploy_compat:v_chipmunk'
include ':deploy_compat:v_giraffe'
include ':deploy_compat:v_hedgehog'
include ':deploy_compat:v_iguana'
include ':deploy_compat:v_meerkat'
include ':deploy_compat:v_narwhal'
include ':deploy_compat:v_narwhal_feature'
include ':deploy_compat:v_otter'
include ':deploy_compat:v_panda'
include ':deploy_compat:v_quail'

include ':platform_compat:base_api'
