rootProject.name = 'jugg'

include ':main'
include ':idea'
include ':jvmti_agent'
include ':aapt2-inclink'
include ':custom_compilers'

include ':deploy_compat:interface'
include ':deploy_compat:v_chipmunk'
include ':deploy_compat:v_giraffe'
include ':deploy_compat:v_hedgehog'
include ':deploy_compat:v_iguana'
include ':deploy_compat:v_meerkat'

include ':platform_compat:base_api'
