package com.sickworm.intellij.jugg.compiler.source

import com.intellij.openapi.diagnostic.Logger
import com.sickworm.intellij.jugg.compiler.CompileError
import com.sickworm.intellij.jugg.compiler.CompileFile
import com.sickworm.intellij.jugg.compiler.CompileResult
import com.sickworm.intellij.jugg.compiler.CompileTask
import com.sickworm.intellij.jugg.compiler.ICompileContext
import com.sickworm.intellij.jugg.compiler.Result
import com.sickworm.intellij.jugg.compiler.databinding.DataBindingArgsManager
import com.sickworm.intellij.jugg.compiler.databinding.DataBindingGenMapperCompiler
import com.sickworm.intellij.jugg.logger.TimeLogger
import com.sickworm.intellij.jugg.project.data.ModuleInfo
import java.io.File

class SourceDataBindingProcessor(
    private val dataBindingGenMapperCompiler: DataBindingGenMapperCompiler,
    private val context: ICompileContext,
    private val logger: Logger,
) {

    /**
     * Process DataBinding Mapper generation after source code compilation
     *
     * This method generates DataBinding implementation classes (XXXBindingImpl, BR, DataBinderMapper)
     * after Java/Kotlin source files are compiled to .class files.
     *
     * @param task The compile task
     * @param module The module info
     * @return CompileResult with generated Java files
     */
    fun processDataBindingMapper(task: CompileTask, module: ModuleInfo): CompileResult {
        val argsManager = DataBindingArgsManager(context, module)
        val isNeedProcessDataBinding = task.files.all {
            it.file == argsManager.dataBindingKaptSourceTrigger
                || it.file == argsManager.dataBindingAptSourceTrigger
        }
        if (!isNeedProcessDataBinding) {
            return CompileResult(task, emptyList(), emptyList())
        }

        // Find layout info files generated by ResourceCompiler
        val layoutInfoFiles = findLayoutInfoFiles(argsManager)
        if (layoutInfoFiles.isEmpty()) {
            logger.debug("No layout info files found, skip DataBinding Mapper generation")
            return CompileResult(task, emptyList(), emptyList())
        }

        logger.info("Processing DataBinding Mapper generation for module ${module.name}...")
        logger.debug("Found ${layoutInfoFiles.size} layout info files")
        TimeLogger.start("databinding_mapper")

        try {
            // Create DataBinding Mapper compilation task
            val sourceFiles = task.files.filter { it.type == CompileFile.Type.Java || it.type == CompileFile.Type.Kotlin }
            val dataBindingTask = CompileTask(
                files = layoutInfoFiles.map {
                    CompileFile(CompileFile.Type.Resource, it, it.parentFile, module)
                } + sourceFiles,
                outputDir = File(context.tempCompileDir, "databinding_mapper"),
                parentTask = task,
            )

            // Generate DataBinding Mapper classes
            val result = dataBindingGenMapperCompiler.compile(dataBindingTask)
            TimeLogger.end("databinding_mapper", logger)

            if (!result.isAllSuccess) {
                logger.warn("DataBinding Mapper generation failed for module ${module.name}.")
            } else {
                logger.info("DataBinding Mapper generation completed for module ${module.name}.")
            }

            return result
        } catch (e: Exception) {
            TimeLogger.end("databinding_mapper", logger)
            logger.warn("DataBinding Mapper generation exception: ${e.message}", e)
            return CompileResult(
                task,
                task.files.map { Result.failure(CompileError(it, listOf(-1L to "DataBinding Mapper generation failed: ${e.message}"))) },
                emptyList()
            )
        }
    }

    /**
     * Find layout info files generated by DataBindingGenBaseClassesCompiler in ResourceCompiler
     *
     * Layout info files are stored in a shared temp directory managed by ResourceOverlayCompiler.
     * We need to look in the overlays/flat_compile/databinding sub-context area, not in our own
     * classes sub-context area.
     *
     * @param module The module info
     * @return List of layout info files (.xml files containing binding information)
     */
    private fun findLayoutInfoFiles(argsManager: DataBindingArgsManager): List<File> {
        // Important: We need to look in the ResourceCompiler's context, not SourceCompiler's context
        // ResourceCompiler uses context.subContext("overlays").subContext("flat_compile").subContext("databinding")
        // So the layout info files are at: {root_tempCompileDir}/overlays/flat_compile/databinding/intermediates/...

        val layoutInfoDir = argsManager.tempDataBindingLayoutXmlDir
        if (!layoutInfoDir.exists()) {
            logger.debug("Layout info directory not found: ${layoutInfoDir.absolutePath}")
            return emptyList()
        }

        val layoutInfoFiles = layoutInfoDir.listFiles()?.filter { it.extension == "xml" } ?: emptyList()
        logger.debug("Found ${layoutInfoFiles.size} layout info files in ${layoutInfoDir.absolutePath}")

        return layoutInfoFiles
    }
}