package com.sickworm.intellij.jugg.compiler.source

import com.intellij.openapi.diagnostic.Logger
import com.sickworm.intellij.jugg.compiler.CompileError
import com.sickworm.intellij.jugg.compiler.CompileFile
import com.sickworm.intellij.jugg.compiler.CompileResult
import com.sickworm.intellij.jugg.compiler.CompileTask
import com.sickworm.intellij.jugg.compiler.ICompileContext
import com.sickworm.intellij.jugg.compiler.Result
import com.sickworm.intellij.jugg.compiler.databinding.DataBindingArgsManager
import com.sickworm.intellij.jugg.compiler.databinding.DataBindingGenMapperCompiler
import com.sickworm.intellij.jugg.compiler.databinding.hasDataBindingAdapterDeclaration
import com.sickworm.intellij.jugg.compiler.source.kotlin.KotlinCompiler
import com.sickworm.intellij.jugg.logger.TimeLogger
import com.sickworm.intellij.jugg.logger.getInstance
import com.sickworm.intellij.jugg.project.data.ModuleInfo
import java.io.File

/**
 * SourceDataBindingProcessor triggers DataBinding mapper generation after source compilation.
 */
class SourceDataBindingProcessor(
    private val dataBindingGenMapperCompiler: DataBindingGenMapperCompiler,
    private val kotlinCompiler: KotlinCompiler,
    private val context: ICompileContext,
    loggerArg: Logger,
) {

    private val logger: Logger = loggerArg.getInstance("SourceDataBindingProcessor")

    private var isCanRetryAfterKotlinCompile = true

    /**
     * Process DataBinding Mapper generation after source code compilation
     *
     * This method generates DataBinding implementation classes (XXXBindingImpl, BR, DataBinderMapper)
     * after Java/Kotlin source files are compiled to .class files.
     *
     * @param task The compile task
     * @param module The module info
     * @return CompileResult with generated Java files
     */
    fun processDataBindingMapper(task: CompileTask, module: ModuleInfo): CompileResult {
        return processDataBindingMapper(task, module, isKotlinAdapterPrepared = false)
    }

    private fun processDataBindingMapper(
        task: CompileTask,
        module: ModuleInfo,
        isKotlinAdapterPrepared: Boolean,
    ): CompileResult {
        val argsManager = DataBindingArgsManager(context, module)
        if (!argsManager.isUseDataBinding) {
            return CompileResult(task, emptyList(), emptyList())
        }
        val kotlinAdapterSources = task.files.filter {
            it.type == CompileFile.Type.Kotlin && it.file.hasDataBindingAdapterDeclaration()
        }
        val hasAdapterDeclaration = task.files.any {
            (it.type == CompileFile.Type.Java || it.type == CompileFile.Type.Kotlin)
                && it.file.hasDataBindingAdapterDeclaration()
        }
        val isNeedProcessDataBinding = hasAdapterDeclaration || task.files.any {
            it.file == argsManager.dataBindingKaptSourceTrigger
                || it.file == argsManager.dataBindingAptSourceTrigger
        }
        if (!isNeedProcessDataBinding) {
            return CompileResult(task, emptyList(), emptyList())
        }

        // Find layout info files generated by ResourceCompiler
        val layoutInfoFiles = findLayoutInfoFiles(argsManager)
        if (layoutInfoFiles.isEmpty() && !hasAdapterDeclaration) {
            logger.debug("No layout info files found, skip DataBinding Mapper generation")
            return CompileResult(task, emptyList(), emptyList())
        }

        logger.info("Processing data binding...")
        logger.debug("Found ${layoutInfoFiles.size} layout info files")
        TimeLogger.start("databinding_mapper")

        try {
            if (kotlinAdapterSources.isNotEmpty() && !isKotlinAdapterPrepared) {
                val prepareResult = prepareKotlinAdapter(task, module, kotlinAdapterSources)
                if (prepareResult != null) {
                    TimeLogger.end("databinding_mapper", logger)
                    return prepareResult
                }
            }

            // Create DataBinding Mapper compilation task
            val sourceFiles = task.files.filter {
                (it.type == CompileFile.Type.Java || it.type == CompileFile.Type.Kotlin)
                    && it !in kotlinAdapterSources
            }
            val hasRemainingAdapterDeclaration = sourceFiles.any { it.file.hasDataBindingAdapterDeclaration() }
            if (layoutInfoFiles.isEmpty() && !hasRemainingAdapterDeclaration) {
                TimeLogger.end("databinding_mapper", logger)
                return CompileResult(task, emptyList(), emptyList())
            }
            val dataBindingTask = CompileTask(
                files = layoutInfoFiles.map {
                    CompileFile(CompileFile.Type.Resource, it, it.parentFile, module)
                } + sourceFiles,
                outputDir = File(context.tempCompileDir, "databinding_mapper"),
                parentTask = task,
            )

            // Generate DataBinding Mapper classes
            val result = dataBindingGenMapperCompiler.compile(dataBindingTask)
            TimeLogger.end("databinding_mapper", logger)

            if (!result.isAllSuccess) {
                val retryKotlinSources = sourceFiles.filter { it.type == CompileFile.Type.Kotlin }
                if (retryKotlinSources.isNotEmpty() && isCanRetryAfterKotlinCompile) {
                    logger.info("DataBinding failed with apt, retry with source compilation one time.")
                    isCanRetryAfterKotlinCompile = false
                    val kotlinCompileTask = CompileTask(
                        files = retryKotlinSources,
                        outputDir = File(context.tempCompileDir, "kotlin"),
                        parentTask = task,
                    )
                    val kotlinCompileResult = kotlinCompiler.compile(kotlinCompileTask)
                    logger.debug("Kotlin compile for databinding retry result: ${kotlinCompileResult.isAllSuccess}")
                    if (kotlinCompileResult.isAllSuccess) {
                        // one more time!
                        return processDataBindingMapper(task, module, isKotlinAdapterPrepared = true)
                    }
                }
                logger.warn("Processing data binding failed.")
            }

            return result
        } catch (e: Exception) {
            TimeLogger.end("databinding_mapper", logger)
            logger.warn("Processing data binding failed with exception: ${e.message}", e)
            return CompileResult(
                task,
                task.files.map { Result.failure(CompileError(it, listOf(-1L to "DataBinding Mapper generation failed: ${e.message}"))) },
                emptyList()
            )
        }
    }

    /**
     * Generates the Kotlin adapter store, compiles the adapter class, then publishes the store.
     * Returns a failed result when either compilation step fails.
     */
    private fun prepareKotlinAdapter(
        task: CompileTask,
        module: ModuleInfo,
        kotlinAdapterSources: List<CompileFile>,
    ): CompileResult? {
        val adapterTask = CompileTask(
            files = kotlinAdapterSources,
            outputDir = File(context.tempCompileDir, "databinding_adapter_store"),
            parentTask = task,
        )
        val storeResult = dataBindingGenMapperCompiler.generateKotlinAdapterStore(adapterTask, module)
        if (!storeResult.isAllSuccess) return storeResult

        val kotlinCompileResult = kotlinCompiler.compile(
            CompileTask(
                files = kotlinAdapterSources,
                outputDir = File(context.tempCompileDir, "kotlin_adapter"),
                parentTask = task,
            ),
        )
        if (!kotlinCompileResult.isAllSuccess) return kotlinCompileResult

        val generatedStore = storeResult.outputs.singleOrNull()?.file
            ?: error("Isolated DataBinding KAPT produced no setter store output")
        dataBindingGenMapperCompiler.mergeKotlinAdapterStore(module, generatedStore)
        return null
    }

    /**
     * Find layout info files generated by DataBindingGenBaseClassesCompiler in ResourceCompiler
     *
     * Layout info files are stored in a shared temp directory managed by ResourceOverlayCompiler.
     * We need to look in the overlays/flat_compile/databinding sub-context area, not in our own
     * classes sub-context area.
     *
     * @param module The module info
     * @return List of layout info files (.xml files containing binding information)
     */
    private fun findLayoutInfoFiles(argsManager: DataBindingArgsManager): List<File> {
        // Important: We need to look in the ResourceCompiler's context, not SourceCompiler's context
        // ResourceCompiler uses context.subContext("overlays").subContext("flat_compile").subContext("databinding")
        // So the layout info files are at: {root_tempCompileDir}/overlays/flat_compile/databinding/intermediates/...

        val layoutInfoDir = argsManager.tempDataBindingLayoutXmlDir
        if (!layoutInfoDir.exists()) {
            logger.debug("Layout info directory not found: ${layoutInfoDir.absolutePath}")
            return emptyList()
        }

        val layoutInfoFiles = layoutInfoDir.listFiles()?.filter { it.extension == "xml" } ?: emptyList()
        logger.debug("Found ${layoutInfoFiles.size} layout info files in ${layoutInfoDir.absolutePath}")

        return layoutInfoFiles
    }
}
