package com.sickworm.intellij.jugg.project

import com.google.gson.Gson
import com.intellij.openapi.diagnostic.Logger
import com.sickworm.intellij.jugg.apk.ApkInfo
import com.sickworm.intellij.jugg.apk.ApkInfoReader
import com.sickworm.intellij.jugg.git.FileMatcher
import com.sickworm.intellij.jugg.server.protocols.ProjectCustomConfig
import java.io.File
import java.util.zip.ZipFile

class CustomConfigManager(
    private val configDir: File,
    private val logger: Logger,
) {

    init {
        configDir.mkdirs()
    }

    private val customConfigFile: File = File(configDir, "custom_config.json")

    private val defaultCustomConfigFile: File = File(configDir, "default_custom_config.json")

    private var cacheKey: String = "null"
    private var configCache: ProjectCustomConfig? = null

    val config: ProjectCustomConfig?
        get() {
            val newCacheKey = getCacheKey()
            if (cacheKey != newCacheKey) {
                logger.debug("Custom config changed from $cacheKey to $newCacheKey, reload it.")
                configCache = loadDefaultConfig()
                cacheKey = newCacheKey
            }
            return configCache
        }

    fun isConfigChanged(): Boolean {
        val newCacheKey = getCacheKey()
        return cacheKey != newCacheKey
    }

    fun updateDefaultConfig(customConfig: ProjectCustomConfig) {
        configDir.mkdirs()

        // avoid updating cacheKey which is generated by lastModified()
        val oldContent = if(defaultCustomConfigFile.exists()) defaultCustomConfigFile.readText() else "{}"
        val newContent = Gson().toJson(customConfig)
        if (oldContent == newContent) {
            logger.debug("No need to update default custom config.")
            return
        }

        defaultCustomConfigFile.writeText(Gson().toJson(customConfig))
    }

    fun fillApkInfosWithEmbeddedApks(apkInfos: List<ApkInfo>, extractDir: File): List<ApkInfo> {
        logger.debug("hasEmbeddedApks: ${hasEmbeddedApks()}")
        if (!hasEmbeddedApks()) {
            return apkInfos
        }

        val finalApkInfos = apkInfos.toMutableList()
        apkInfos.forEach { apkInfo ->
            apkInfo.files.forEach { apkFileUnit ->
                val embeddedApks = extractEmbeddedApks(apkFileUnit.apkFile, extractDir)
                logger.debug("find embeddedApks for ${apkFileUnit.apkFile}, result: $embeddedApks")
                val embeddedApkInfos = ApkInfoReader(logger).createApkInfo(embeddedApks)
                embeddedApkInfos.forEach { embApkInfo ->
                    val existsApkInfo = apkInfos.find { it.applicationId == embApkInfo.applicationId }
                    if (existsApkInfo == null) {
                        finalApkInfos.add(embApkInfo)
                    } else {
                        finalApkInfos.remove(existsApkInfo)
                        finalApkInfos.add(existsApkInfo.copy(files = existsApkInfo.files + embApkInfo.files))
                    }
                }
            }
        }
        logger.debug("finalApkInfos: $finalApkInfos")
        return finalApkInfos
    }

    fun hasEmbeddedApks(): Boolean {
        return config?.embeddedApksSearchRules?.isNotEmpty() ?: false
    }

    private fun extractEmbeddedApks(apkFile: File, outputDir: File): List<File> {
        val rules = config?.embeddedApksSearchRules ?: return emptyList()
        if (rules.isEmpty()) {
            return emptyList()
        }
        val fileMatcher = FileMatcher().also {
            it.init(null, rules)
        }

        ZipFile(apkFile).use { zipFile ->
            val result = mutableListOf<File>()
            zipFile.entries().asIterator().forEach {
                val entryName = it.name
                if (fileMatcher.isMatch(it.name)) {
                    val outputFile = File(outputDir, apkFile.name + "_" + entryName)
                    outputFile.parentFile.mkdirs()
                    logger.debug("found embedded apk: $entryName in $apkFile, output to: $outputFile")
                    zipFile.getInputStream(it).use { inputStream ->
                        outputFile.outputStream().use { outputStream ->
                            inputStream.copyTo(outputStream)
                        }
                    }
                    outputFile.setLastModified(it.time)
                    result.add(outputFile)
                }
            }
            return result
        }
    }

    private fun loadDefaultConfig(): ProjectCustomConfig? {
        if (customConfigFile.exists()) {
            try {
                val result = Gson().fromJson(customConfigFile.readText(), ProjectCustomConfig::class.java)
                logger.debug("Load custom config: $result")
                return result
            } catch (e: Exception) {
                logger.warn("Load custom config failed.", e)
            }
        }

        if (defaultCustomConfigFile.exists()) {
            try {
                val result = Gson().fromJson(defaultCustomConfigFile.readText(), ProjectCustomConfig::class.java)
                logger.debug("Load default custom config: $result")
                return result
            } catch (e: Exception) {
                logger.warn("Load default custom config failed.", e)
            }
        }

        logger.debug("No custom config found.")
        return null
    }

    private fun getCacheKey(): String {
        return listOf(
            if (customConfigFile.exists()) customConfigFile.lastModified() else 0,
            if (defaultCustomConfigFile.exists()) defaultCustomConfigFile.lastModified() else 0,
        ).joinToString("_")
    }
}