buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.2'
    }
}

import com.android.tools.r8.D8
import com.android.tools.r8.D8Command
import com.android.tools.r8.origin.Origin

import java.nio.file.Files
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

File jarFile = new File(project.projectDir, "build/intermediates/aar_main_jar/release/classes.jar")
File instrumentsJarFile = new File(project.projectDir, "build/outputs/jugg-instruments.jar")
File agentSoFile = new File(project.projectDir, "build/intermediates/library_and_local_jars_jni/release/jni/arm64-v8a/jugg_jvmti_agent.so")
File setupScriptFile = new File(project.projectDir, "src/main/script/jugg_agent_setup.sh")
String agentBundlePath = "/deploy/jugg-agent-bundle-${agentVersion}.zip" // must starts with '/' to read resource by plugin
File agentBundleFile = new File(agentBundleDir, agentBundlePath)
String runtimeJarPath = "/deploy/jugg-runtime.jar"
File runtimeJarFile = new File(agentBundleDir, runtimeJarPath)

android {
    defaultConfig {
        buildConfigField("String", "AGENT_VERSION", "\"$agentVersion\"")
        buildConfigField("String", "AGENT_BUNDLE_PATH", "\"$agentBundlePath\"")
        buildConfigField("String", "RUNTIME_JAR_PATH", "\"$runtimeJarPath\"")
        buildConfigField("String", "META_DATA_LABEL_RAW_APPLICATION", "\"com.sickworm.intellij.jugg.hotfix.raw.application\"")
        buildConfigField("String", "INJECT_APPLICATION_NAME", "\"com.sickworm.intellij.jugg.hotfix.BootstrapApplication\"")
        buildConfigField("String", "RESOURCE_APK_NAME", "\"resource.ap_\"")
        buildConfigField("String", "JVMTI_NOT_AVAILABLE_FLAG_FILE", "\".jugg_jvmti_not_available\"")
        buildConfigField("String", "ENABLE_COMPAT_DEPLOY_FLAG_FILE", "\".jugg_compat_deploy_enable\"")
    }
}

tasks.register('buildInstrumentJar') {

    inputs.file jarFile
    outputs.file instrumentsJarFile

    doLast {
        if (!jarFile.exists()) {
            throw new IllegalStateException("jarFile $jarFile not exists")
        }

        instrumentsJarFile.parentFile.mkdirs()
        instrumentsJarFile.delete()

        String[] args = "--min-api 26 --output $instrumentsJarFile $jarFile".split(' ')
        D8Command command = D8Command
                .parse(args, Origin.root())
                .build()
        D8.run(command)
    }

    it.dependsOn('assembleRelease')
}

tasks.register('buildAgentBundle') {

    inputs.files instrumentsJarFile, agentSoFile, setupScriptFile, jarFile
    outputs.dir agentBundleDir

    doLast {
        agentBundleDir.deleteDir()
        agentBundleFile.parentFile.mkdirs()

        ZipOutputStream zipOutputStream = new ZipOutputStream(new FileOutputStream(agentBundleFile))
        [instrumentsJarFile, agentSoFile, setupScriptFile].forEach { file ->
            FileInputStream fileInputStream = new FileInputStream(file)
            ZipEntry zipEntry = new ZipEntry(file.getName())
            zipOutputStream.putNextEntry(zipEntry)

            byte[] buffer = new byte[1024]
            int length
            while ((length = fileInputStream.read(buffer)) > 0) {
                zipOutputStream.write(buffer, 0, length)
            }

            zipOutputStream.closeEntry()
            fileInputStream.close()
        }
        zipOutputStream.close()

        runtimeJarFile.delete()
        Files.copy(jarFile.toPath(), runtimeJarFile.toPath())
    }

    it.dependsOn('generateDebugBuildConfig') // generate debug BuildConfig to show IDE tint
    it.dependsOn('assembleRelease')
    it.dependsOn('buildInstrumentJar')
}
