// use to read variables in gradle environment
// usage: ./gradlew :app:assembleDebug -I init.gradle

private void readAndSave() {
    File recordFile = new File(rootProject.rootDir, "build/jugg/gradle/result.json")
    try {
        println("Jugg: init.gradle execute start")
        deleteRecordFile()
        String result = readEnv()
        writeRecordFile(result)
        println("Jugg: init.gradle execute success, output file: $recordFile")
    } catch (Throwable e) {
        println("Jugg: init.gradle execute failed:")
        println("$e")
        def outputStream = new ByteArrayOutputStream()
        e.printStackTrace(new PrintStream(outputStream))
        def result = outputStream.toString()
        def lines = result.split('\n')
        for (String line : lines) {
            if (line.contains("init.gradle")) {
                println(line)
            }
        }
    }
}

private void deleteRecordFile() {
    File recordFile = new File(rootProject.rootDir, "build/jugg/gradle/result.json")
    recordFile.delete()
}

private void writeRecordFile(String result) {
    File recordFile = new File(rootProject.rootDir, "build/jugg/gradle/result.json")
    recordFile.getParentFile().mkdirs()
    recordFile.createNewFile()
    recordFile.write(result)
}

private String readEnv() {
    println("rootProject.subprojects.size() " + rootProject.subprojects.size())
    println(rootProject.subprojects)
    // Cannot get property 'android' on null object, if app has no android extension
//        def manifestPlaceholders = rootProject.findProject("app").android.defaultConfig.manifestPlaceholders["qq_app_id"]
//        println(manifestPlaceholders)

    String result = """{ "applicationModule": "app" }"""
    return result
}

gradle.projectsEvaluated {
    readAndSave()
}