package com.sickworm.intellij.jugg.compiler

import com.android.tools.idea.run.ApkInfo
import com.intellij.openapi.Disposable
import com.intellij.openapi.diagnostic.Logger
import com.sickworm.intellij.jugg.project.JuggInternalException
import com.sickworm.intellij.jugg.project.data.ModuleInfo
import com.sickworm.intellij.jugg.project.data.SigningConfig
import java.io.File

class CompileTask(
    val files: List<CompileFile>,
    val outputDir: File,
    private val parentTask: CompileTask?,
    private val compileStatusHolder: CompileStatusHolder,
) {

    constructor(files: List<CompileFile>, outputDir: File, compileStatusHolder: CompileStatusHolder):
            this(files, outputDir, null, compileStatusHolder)

    constructor(files: List<CompileFile>, outputDir: File, parentTask: CompileTask):
            this(files, outputDir, parentTask, parentTask.compileStatusHolder)

    val isShouldCancel: Boolean get() = compileStatusHolder.isShouldCancel

    fun notifyCompiled(files: List<CompileFile>) {
        compileStatusHolder.onFilesCompiled(files)
    }

    val isNeedCompile get() = files.isNotEmpty()

    override fun equals(other: Any?): Boolean {
        return if (other is CompileTask) {
            files == other.files
                    && outputDir == other.outputDir
                    && parentTask == other.parentTask
                    && compileStatusHolder == other.compileStatusHolder
        } else {
            false
        }
    }

    override fun hashCode(): Int {
        return files.hashCode() + outputDir.absolutePath.hashCode() + parentTask.hashCode() + compileStatusHolder.hashCode()
    }

    operator fun plus(task: CompileTask): CompileTask {
        if (!outputDir.isParentOf(task.outputDir)) {
            val reason = "Output dir not matched, origin: $outputDir, combined: ${task.outputDir}"
            throw JuggInternalException.combineTaskFailed(reason)
        }
        if (this != task.parentTask) {
            if (this.compileStatusHolder != task.compileStatusHolder) {
                val reason = "isShouldCancelCallback not the same"
                throw JuggInternalException.combineTaskFailed(reason)
            }
            if (this.parentTask != task.parentTask) {
                val reason = "parentTask not the same"
                throw JuggInternalException.combineTaskFailed(reason)
            }
        }
        return CompileTask(files + task.files.filter { !files.contains(it)}, outputDir, parentTask, compileStatusHolder)
    }

    private fun File.isParentOf(file: File) = file.path.startsWith(path)

    companion object
}

data class CompileFile(
    val type: Type,
    val file: File,
    val baseDir: File,
    val module: ModuleInfo,
    val extraInfo: Map<String, Any> = emptyMap(),
    val dependencyPaths: List<String> = emptyList(), // extra dependency paths, default use module's dependencies in CompileContext
) {

    val relativeFile get() = file.absoluteFile.relativeTo(baseDir)

    override fun toString(): String {
        return "$type:${file.name}"
    }

    enum class Type {
        Java,
        Kotlin,
        Class,
        Asset,
        NativeLib,
        Resource,
        Flat,
        BuildFile,
        AndroidManifest,
        DexToChangePackageName,
        ;

    }
}

data class CompileOutput(
    val type: Type,
    val file: File,
    val baseDir: File,
) {

    val relativeFile get() = file.absoluteFile.relativeTo(baseDir)

    enum class Type {
        Class,
        Dex,
        Res, // includes res/**, AndroidManifest.xml, resource.arsc
        Asset, // includes assets/**, and all other files except Dex and Res
        NativeLib, // includes lib/**
        Java, // R.java generated by aapt2, or file generated by APT
        ;
    }

    override fun toString(): String {
        return "$type:${file.relativeTo(baseDir)}"
    }
}

data class CompileResult(
    val task: CompileTask,
    val details: List<Result<CompileFile, CompileError>>,
    val outputs: List<CompileOutput>
) {
    val successFiles get() = details.filter { it.isSuccess }

    val failedFiles get() = details.filter { it.isFailed }

    val isAllSuccess get() = details.all { it.isSuccess }

    operator fun plus(result: CompileResult): CompileResult {
        return CompileResult(
            task + result.task,
            details + result.details,
            outputs + result.outputs
        )
    }

    val compiledFailedFiles get() = details.filter { it.isFailed && it.getFailure().errors != quickFailedErrors }
    val notCompiledFiles get() = details.filter { it.isFailed && it.getFailure().errors == quickFailedErrors }

    fun quickFailedOthers(parentTask: CompileTask, isClearOutput: Boolean = false): CompileResult {
        val details: List<Result<CompileFile, CompileError>> = parentTask.files.map { file ->
            val compiledDetails = details.find { it.file == file }
            if (compiledDetails != null) {
                return@map compiledDetails
            } else {
                return@map Result.failure(CompileError(file, quickFailedErrors))
            }
        }
        return CompileResult(
            parentTask,
            details,
            if (isClearOutput) emptyList() else outputs
        )
    }

    companion object {
        private val quickFailedErrors = listOf(-1L to "quick failed")
    }
}

val Result<CompileFile, CompileError>.file: CompileFile
    get() = if (isSuccess) getOrNull()!! else getFailureOrNull()!!.file

data class CompileError(
    /** file to be compiled */
    val file: CompileFile,
    /** will be empty if [file] looks good but compiler still stopped because there is another error file */
    val errors: List<Pair<Long, String>> // <Line, Message>
) {
    val errorMessages get() = errors.joinToString("\n") { it.second }
}

interface ICompiler: Disposable {
    val supportedTypes: List<CompileFile.Type>

    fun compile(task: CompileTask): CompileResult

    fun warmUp() = Unit

    /**
     * for custom compiler, if return true, it will be executed before normal compile
     */
    val isBeforeNormalCompile: Boolean get() = false

    /**
     * consume compile files
     * @return the rest files that should be compiled by other compilers
     */
    fun consumeFiles(files: List<CompileFile>): List<CompileFile> = files
}

interface ICompileContext {
    /** logg printer */
    val logger: Logger
    /** compile temporary directory */
    val tempCompileDir: File
    /** temporary module directory for generating something that no belong to any modules*/
    val tempModuleDir: File
    /** Android sdk dir */
    val androidHome: File
    /** android.jar */
    val androidJar: File
    /** modules in project */
    val modules: Map<String, ModuleInfo>
    /** deployed base apks */
    val apkInfos: List<ApkInfo>
    /** project root directory, for log print */
    val projectDir: File
    /** all deployed files */
    val deployedFiles: List<CompileOutput>
    /** APK singing config */
    val signingConfig: SigningConfig?

    val packageName get() = apkInfos.firstOrNull()?.applicationId

    val apkFile: File? get() = apkInfos.firstOrNull()?.files?.first()?.apkFile

    val tempModule: ModuleInfo

    val applicationModule: ModuleInfo?

    val isEnableDesugared: Boolean

    val modulesWithOrder: List<ModuleInfo>

    val cmdCompileEnv: List<String>

    fun getModuleDependencies(moduleInfo: ModuleInfo, task: CompileTask): List<String>

    fun getGeneratedSourcePaths(moduleInfo: ModuleInfo): List<File>

    fun getAllDesugarClasspath(compileFiles: List<CompileFile>, moduleInfo: ModuleInfo, toDir: File)

    fun getLastBuildAndroidManifest(file: CompileFile): File?

    fun listenUpdate(listener: OnContextUpdate)

    fun printClasspathCheck(moduleInfo: ModuleInfo)
}

fun ICompileContext.subContext(subTempCompileDirName: String): ICompileContext {
    val origin = this
    return object : ICompileContext by origin {
        override val tempCompileDir: File
            get() = File(origin.tempCompileDir, subTempCompileDirName)
    }
}

typealias OnContextUpdate = () -> Unit

