@file:Suppress("unused")

package com.sickworm.intellij.jugg.compiler

import com.sickworm.intellij.jugg.apk.ApkInfo
import com.intellij.openapi.Disposable
import com.intellij.openapi.diagnostic.Logger
import com.sickworm.intellij.jugg.apk.ApkFileUnit
import com.sickworm.intellij.jugg.project.JuggInternalException
import com.sickworm.intellij.jugg.project.data.ModuleInfo
import com.sickworm.intellij.jugg.project.data.SigningConfig
import java.io.File

class CompileTask(
    val files: List<CompileFile>,
    val outputDir: File,
    private val parentTask: CompileTask?,
    private val compileStatusHolder: CompileStatusHolder,
) {

    constructor(files: List<CompileFile>, outputDir: File, compileStatusHolder: CompileStatusHolder):
            this(files, outputDir, null, compileStatusHolder)

    constructor(files: List<CompileFile>, outputDir: File, parentTask: CompileTask):
            this(files, outputDir, parentTask, parentTask.compileStatusHolder)

    val isShouldCancel: Boolean get() = compileStatusHolder.isShouldCancel

    fun notifyCompiled(files: List<CompileFile>) {
        compileStatusHolder.onFilesCompiled(files)
    }

    val isNeedCompile get() = files.isNotEmpty()

    override fun equals(other: Any?): Boolean {
        return if (other is CompileTask) {
            files == other.files
                    && outputDir == other.outputDir
                    && parentTask == other.parentTask
                    && compileStatusHolder == other.compileStatusHolder
        } else {
            false
        }
    }

    override fun hashCode(): Int {
        return files.hashCode() + outputDir.absolutePath.hashCode() + parentTask.hashCode() + compileStatusHolder.hashCode()
    }

    operator fun plus(task: CompileTask): CompileTask {
        if (!outputDir.isParentOf(task.outputDir)) {
            val reason = "Output dir not matched, origin: $outputDir, combined: ${task.outputDir}"
            throw JuggInternalException.combineTaskFailed(reason)
        }
        if (this != task.parentTask) {
            if (this.compileStatusHolder != task.compileStatusHolder) {
                val reason = "isShouldCancelCallback not the same"
                throw JuggInternalException.combineTaskFailed(reason)
            }
            if (this.parentTask != task.parentTask) {
                val reason = "parentTask not the same"
                throw JuggInternalException.combineTaskFailed(reason)
            }
        }
        return CompileTask(files + task.files.filter { !files.contains(it)}, outputDir, parentTask, compileStatusHolder)
    }

    fun allFailed(error: String): CompileResult {
        val details: List<Result<CompileFile, CompileError>> = this.files.map {
            Result.failure(CompileError(it, listOf(-1L to error)))
        }
        return CompileResult(this, details, emptyList(),)
    }

    private fun File.isParentOf(file: File) = file.path.startsWith(path)

    override fun toString(): String {
        return "CompileTask(files=${files.map { it.file.name }}, outputDir=${outputDir.name})"
    }

    companion object
}

data class CompileFile(
    val type: Type,
    val file: File,
    val baseDir: File,
    val module: ModuleInfo,
    val extraInfo: Map<String, Any> = emptyMap(),
    val dependencyPaths: List<String> = emptyList(), // extra dependency paths, default use module's dependencies in CompileContext
) {

    val relativeFile get() = file.absoluteFile.relativeTo(baseDir)

    override fun toString(): String {
        return "$type:${file.name}"
    }

    enum class Type {
        Java,
        Kotlin,
        Class,
        Asset,
        NativeLib,
        Resource,
        Flat,
        BuildFile,
        AndroidManifest,
        DexToChangePackageName,
        Dex,
        ;

    }
}

data class CompileOutput(
    val type: Type,
    val file: File,
    val baseDir: File,
    val apkPath: String? = null,
    val relativeModule: ModuleInfo? = null, // optional, now only use for generated java class of databinding
) {

    val relativeFile get() = file.absoluteFile.relativeTo(baseDir)

    enum class Type {
        Class,
        Flat, // flat file generated by aapt2
        Dex,
        Res, // includes res/**, AndroidManifest.xml, resource.arsc
        Asset, // includes assets/**, and all other files except Dex and Res
        NativeLib, // includes lib/**
        Java, // R.java generated by aapt2, or file generated by APT
        Kotlin, // file generated by ksp
        ResXml, // split layout xml files generated by data binding
        OtherNotDeployed, // other files like middle compilation files that will not deploy to device
        ;
    }

    override fun toString(): String {
        return "$type:${file.relativeTo(baseDir)}"
    }
}

data class CompileResult(
    val task: CompileTask,
    val details: List<Result<CompileFile, CompileError>>,
    val outputs: List<CompileOutput>
) {
    val successFiles get() = details.filter { it.isSuccess }

    val failedFiles get() = details.filter { it.isFailed }

    val isAllSuccess get() = details.all { it.isSuccess }

    operator fun plus(result: CompileResult): CompileResult {
        return CompileResult(
            task + result.task,
            details + result.details,
            outputs + result.outputs
        )
    }

    val compiledFailedFiles get() = details.filter { it.isFailed && it.getFailure().errors != quickFailedErrors }
    val notCompiledFiles get() = details.filter { it.isFailed && it.getFailure().errors == quickFailedErrors }

    fun quickFailedOthers(parentTask: CompileTask,
                          isClearOutput: Boolean = false,
                          otherFailedFiles: List<CompileFile> = emptyList(),
    ): CompileResult {
        val details: List<Result<CompileFile, CompileError>> = parentTask.files.map { file ->
            val compiledDetail = details.find { it.file == file }
            if (compiledDetail != null) {
                if (otherFailedFiles.any { it.file.path == compiledDetail.file.file.path }) {
                    return@map Result.failure(CompileError(file, quickFailedErrors))
                } else {
                    return@map compiledDetail
                }
            } else {
                return@map Result.failure(CompileError(file, quickFailedErrors))
            }
        }
        val result = CompileResult(
            parentTask,
            details,
            if (isClearOutput) emptyList() else outputs
        )
        return if (result.isAllSuccess) {
            // which means failed files is middle generated files. mark all failed to make sure result is right.
            parentTask.allFailed("quickFailedOthers_all_failed")
        } else {
            CompileResult(
                parentTask,
                details,
                if (isClearOutput) emptyList() else outputs
            )
        }
    }

    companion object {
        private val quickFailedErrors = listOf(-1L to "quick failed")

        fun empty(compileStatusHolder: CompileStatusHolder): CompileResult {
            return CompileResult(
                CompileTask(emptyList(), File(""), compileStatusHolder),
                emptyList(),
                emptyList(),
            )
        }

        fun empty(compileTask: CompileTask): CompileResult {
            return CompileResult(compileTask, emptyList(), emptyList())
        }
    }
}

val Result<CompileFile, CompileError>.file: CompileFile
    get() = if (isSuccess) getOrNull()!! else getFailureOrNull()!!.file

data class CompileError(
    /** file to be compiled */
    val file: CompileFile,
    /** will be empty if [file] looks good but compiler still stopped because there is another error file */
    val errors: List<Pair<Long, String>> // <Line, Message>
) {
    val errorMessages get() = errors.joinToString("\n") { it.second }
}

interface ICompiler: Disposable {
    val supportedTypes: List<CompileFile.Type>

    fun compile(task: CompileTask): CompileResult

    fun warmUp() = Unit

    /**
     * for custom compiler execute point
     */
    val order: Int get() = NO_ORDER

    /**
     * consume compile files to avoid some files compile by other compilers
     * @return the rest files that should be compiled by other compilers
     */
    fun consumeFiles(files: List<CompileFile>): List<CompileFile> = files

    companion object {
        const val NO_ORDER = 0
    }
}

interface ICompileContext {
    /** logg printer */
    val logger: Logger
    /** compile temporary directory */
    val tempCompileDir: File
    /** temporary module directory for generating something that no belong to any modules*/
    val tempModuleDir: File
    /** Android sdk dir */
    val androidHome: File
    /** android.jar */
    val androidJar: File
    /** modules in project */
    val modules: Map<String, ModuleInfo>
    /** deployed base apks */
    val apkInfos: List<ApkInfo>
    /** project root directory, for log print */
    val projectDir: File
    /** all deployed files */
    val deployedFiles: List<CompileOutput>
    /** APK singing config */
    val signingConfig: SigningConfig?

    /** compile temporary incremental storage directory */
    val incrementalDataDir: File

    // use the shortest package name to filter dynamic feature package
    val packageName get() = apkInfos.minByOrNull { it.applicationId.length }?.applicationId

    val isSingleApk get() = apkInfos.flatMap { it.files }.map { it.apkFile }.size == 1

    val isReleaseApk get() = applicationModule?.buildVariant?.contains("release", ignoreCase = true) == true

    val isDebuggable get() = apkInfos.flatMap { it.files }.filter { it.isBaseApk }.all { it.debuggable }

    val mappingFile get() = applicationModule?.buildPathInfo?.mappingFile

    val isMinified get() = mappingFile?.exists() == true

    val tempModule: ModuleInfo

    val applicationModule: ModuleInfo?

    val dynamicFeatureModules: List<ModuleInfo>

    val isEnableDesugared: Boolean

    val modulesWithOrder: List<ModuleInfo>

    val moduleBelongsApkMap: Map<ModuleInfo, ApkFileUnit>

    val cmdCompileEnv: List<String>

    val scene: Scene

    val customCompilers: List<ICompiler>

    fun getModuleDependencies(moduleInfo: ModuleInfo, task: CompileTask): List<String>

    fun getGeneratedSourcePaths(moduleInfo: ModuleInfo): List<File>

    fun getDesugarInfo(compileFiles: List<CompileFile>, moduleInfo: ModuleInfo, toDir: File): DesugarInfo

    fun getLastBuildAndroidManifest(file: CompileFile): File?

    fun getParentModules(moduleInfo: ModuleInfo, isAddSelfToResult: Boolean): List<ModuleInfo>

    fun listenUpdate(listener: OnContextUpdate)

    fun printClasspathCheck(moduleInfo: ModuleInfo)

    fun getModulePackageName(moduleInfo: ModuleInfo): String?

    fun backupGradleDir(sourceDir: File, overrideOnExists: Boolean = false, dryRun: Boolean = false): File

    enum class Scene {
        IDE,
        INCREMENTAL_APK,
    }
}

data class DesugarInfo(
    val allInterfacesWithDefaultMethod: List<String>,

    /**
     * Map<origin class name, rewritten class name>
     *
     * see https://stackoverflow.com/questions/66556819/android-corelibrarydesugaring-which-java-11-apis-can-i-expect-to-work
     * see https://r8.googlesource.com/r8/+/314402df87d70a4ad2b6a075c4af0849b33c5830/src/library_desugar/desugar_jdk_libs.json
     */
    val coreLibraryRewriteClassMap: Map<String, String>,

    val isNeedRewriteCoreLibrary: Boolean,

    val desugaredLibraryConfiguration: String?,
) {

    override fun toString(): String {
        return "isNeedRewriteCoreLibrary=$isNeedRewriteCoreLibrary, " +
                "coreLibraryRewriteClassMap=${coreLibraryRewriteClassMap.size}, " +
                "allInterfacesWithDefaultMethod=${allInterfacesWithDefaultMethod.size}, " +
                "desugaredLibraryConfiguration=${desugaredLibraryConfiguration?.length}"
    }

    companion object {
        val EMPTY = DesugarInfo(emptyList(), emptyMap(), false, null)
    }
}

typealias OnContextUpdate = () -> Unit

