plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'java'
}

sourceCompatibility = 11
targetCompatibility = 11

compileKotlin {
    kotlinOptions.jvmTarget = "11"
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    // for using org.apache.tools.zip.ZipEntry
    // java.util.zip.ZipEntry throws exceptions in some situation
    api "org.apache.ant:ant:1.10.11"
}
