plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'java'
    id 'org.jetbrains.intellij'
}

intellij {
    version = ide_version
}

repositories {
    google()
    mavenCentral()

    flatDir {
        dirs 'libs'
    }
}

dependencies {
    compileOnly fileTree(dir: 'libs', include: ['*.jar'])

    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    implementation project(':deploy_compat:interface')
    api project(':deploy_compat:v_chipmunk')
}

test {
    useJUnitPlatform()
}