plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'java'
    id 'org.jetbrains.intellij'
}

buildSearchableOptions {
    enabled = false
}

intellij {
    version = ide_version
    plugins = ['android']
}

repositories {
    google()
    mavenCentral()

    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(dir: '../../libs', include: ['*.jar'])

    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

test {
    useJUnitPlatform()
}