plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'java'
    id 'org.jetbrains.intellij'
}

intellij {
    version = '212.5712.43' // Android Studio Chipmunk
    plugins = ['android']
}

repositories {
    google()
    mavenCentral()

    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(dir: '../libs', include: ['*.jar'])

    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    implementation project(':deploy_compat:interface')
}

test {
    useJUnitPlatform()
}